#!/usr/bin/env bash
dir=`dirname $0`
header_filter="`realpath $dir`/services/|`realpath $dir`/test/|`realpath $dir`/cli/|`realpath $dir`/pipelines/"
clang_tidy="clang-tidy;-header-filter=$header_filter"

files() {
    find {services,test,cli,pipelines} \
         -name '*.cpp' \
         -o -name '*.hpp' \
         -o -name CMakeLists.txt \
         -o -name .clang-tidy \
 	 | grep -vE '\.#|~$|#$'
}

mkdir -p build

while true; do
    (cd build \
         && cmake .. \
		              --graphviz=trawler.dot \
		              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		              -DCMAKE_BUILD_TYPE=Debug \
		              -DTRAWLER_ENABLE_SANITIZERS=OFF \
	       && make -j`nproc` \
         && ./cli/trawler --loglevel debug ../examples/bitcoin.yaml)
#         && ./test/pipelines/buffer/trawler-pipelines-buffer-test)
	 
    inotifywait -e modify `files`
done

