---
title: Bitcoin Example

services:
  - name: bitcoin-client
    service: websocket-client
    host: api.bitfinex.com
    port: 443
    target: /ws
    ssl: true

pipelines:
  - name: inja-pipeline
    pipeline: inja
    source: bitcoin-client
    event: data
    template: "Hello World"
    
endpoints:
  - name: subscribe
    source: bitcoin-client
    event: connected
    data: '{ "event": "subscribe", "channel": "ticker", "pair": "BTCUSD" }'
  - name: terminate
    source: inja-pipeline
    event: data
  
