---
title: Bitcoin Example

services:
  - name: bitcoin-client
    service: websocket-client
    host: api.bitfinex.com
    port: 443
    target: /ws
    ssl: true

pipelines:
  - name: subscribe
    pipeline: reply
    source: bitcoin-client
    event: connected
    data: '{ "event": "subscribe", "channel": "ticker", "pair": "BTCUSD" }'
      
  
